(() => {
  const P = window.MOAAZ_PUBLIC;
  const projects = (window.PORTFOLIO?.projects || []).map(p => ({...p}));
  const I18N = {
    en: {
      navHome:'Home',navProjects:'Projects',navAbout:'About',navContact:'Contact',navSkills:'Skills',navDashboard:'Dashboard',menuTitle:'Navigate',
      heroEyebrow:'FULL STACK DEVELOPER / WEB CREATOR',heroGreeting:"Hi, I'm",heroTitle:'Full Stack Developer & Web Creator',heroSentence:'Building ideas into modern web experiences.',heroDesc:'I build real websites, learn by creating, and turn ideas into clean digital experiences with modern web tools.',viewProjects:'View Projects',contactMe:'Contact Me',openTo:'Open to opportunities & collaborations',currentlyUsing:'CURRENTLY USING',currentlyLearning:'CURRENTLY LEARNING',scrollExplore:'Scroll to explore',introLabel:'A little about me',introHeading:'I build, learn,<br><em>and keep moving.</em>',introText:"I'm Moaaz Tamer, a young web developer focused on building real websites, learning modern technologies, and turning ideas into practical digital experiences.",readAbout:'Read my story ↗',featuredHeading:'Featured projects',viewAll:'View all projects ↗',skillsHeading:'Skills & learning',viewSkills:'Explore skills ↗',ctaHeading:"Have an idea?<br><em>Let's build it.</em>",startConversation:'Start a conversation',footerRole:'Full Stack Developer & Web Creator',footerCta:"Let's talk ↗",
      projectsEyebrow:'SELECTED WORK',projectsHeading:'Real projects.<br><em>Real practice.</em>',projectsIntro:'A collection of websites I built to practice, experiment, and turn ideas into working experiences.',projectCountLabel:'projects',searchPlaceholder:'Search projects...',noResults:'No projects found.',tryAgain:'Try another keyword.',explore:'Explore',
      aboutEyebrow:'ABOUT ME',aboutHeading:'The person<br><em>behind the code.</em>',aboutLead:"I'm a young web developer who learns by building real things.",aboutTitle:'I like turning ideas into websites people can actually use.',aboutBody:"I enjoy taking an idea from a blank page to a working website. Most of my experience comes from building real projects, experimenting with interfaces, and learning by shipping. I currently work with HTML, CSS, JavaScript and Firebase, while using GitHub to publish my work and AI tools to help with parts of the development process.",aboutBody2:"My next learning steps are React and Bootstrap. I don't want to stop at knowing syntax — I want to keep improving how I think about structure, interaction, performance and the overall experience.",value1Title:'Build for real',value1Text:'Projects are my way of learning. I prefer making something functional and improving it through practice.',value2Title:'Keep learning',value2Text:'Web development keeps changing, so I keep adding tools and ideas to my workflow.',value3Title:'Care about details',value3Text:'Clean spacing, clear hierarchy and useful interactions can make a simple website feel much better.',quote:'“Keep building. Every project teaches you something the last one could not.”',
      skillsEyebrow:'SKILLS',skillsPageHeading:'Tools I use<br><em>and learn.</em>',skillsPageIntro:"A clear look at the technologies in my current workflow and the ones I'm learning next.",currentSkillsTitle:'Currently using',currentSkillsText:'Technologies I use in my projects today.',learningTitle:'Currently learning',learningText:"The next tools I'm adding to my development toolkit.",skillNoteTitle:'No fake percentages.<br><em>Just honest progress.</em>',skillNoteText:'I prefer showing what I actually use and what I am currently learning instead of inventing experience levels.',
      contactEyebrow:'GET IN TOUCH',contactHeading:"Let's build<br><em>something real.</em>",contactIntro:'Have a project, collaboration, or an idea you want to discuss? Send me a message.',phoneLabel:'PHONE',callNow:'Call me ↗',whatsappCta:'Message on WhatsApp ↗',youtubeCta:'Visit channel ↗',formHeading:'Send me<br><em>a message.</em>',formIntro:"Fill in the form and your message will be sent through the site's existing messaging system.",formName:'Name',formEmail:'Email',formMessage:'Message',formSend:'Send Message',contactBottomTitle:'Open to new opportunities,<br><em>collaborations & web projects.</em>',seeWork:'See my work',backProjects:'← Back to projects',
      signedOut:'Please sign in before sending a message. Your message stays connected to your account.',sent:'Message sent successfully.',formError:'Something went wrong. Please try again.',messageRequired:'Please complete all fields.',projectNotFound:'Project not found.'
    },
    ar: {
      navHome:'الرئيسية',navProjects:'المشاريع',navAbout:'عني',navContact:'تواصل',navSkills:'المهارات',navDashboard:'لوحة التحكم',menuTitle:'التنقل',
      heroEyebrow:'مطور FULL STACK / صانع تجارب ويب',heroGreeting:'مرحبًا، أنا',heroTitle:'مطور Full Stack وصانع تجارب ويب',heroSentence:'أحوّل الأفكار إلى تجارب ويب عصرية.',heroDesc:'أبني مواقع حقيقية، وأتعلم من خلال التنفيذ، وأحوّل الأفكار إلى تجارب رقمية نظيفة باستخدام أدوات الويب الحديثة.',viewProjects:'استعرض المشاريع',contactMe:'تواصل معي',openTo:'متاح للفرص والتعاون والمشاريع الجديدة',currentlyUsing:'أستخدم حاليًا',currentlyLearning:'أتعلم حاليًا',scrollExplore:'مرر للاستكشاف',introLabel:'نبذة عني',introHeading:'أبني، أتعلم،<br><em>وأواصل التقدم.</em>',introText:'أنا معاذ تامر، مطور ويب شاب أركز على بناء مواقع حقيقية، وتعلم التقنيات الحديثة، وتحويل الأفكار إلى تجارب رقمية عملية.',readAbout:'اقرأ قصتي ↗',featuredHeading:'مشاريع مميزة',viewAll:'عرض كل المشاريع ↗',skillsHeading:'المهارات والتعلم',viewSkills:'استكشف المهارات ↗',ctaHeading:'عندك فكرة؟<br><em>خلينا نبنيها.</em>',startConversation:'ابدأ محادثة',footerRole:'مطور Full Stack وصانع تجارب ويب',footerCta:'تواصل معي ↗',
      projectsEyebrow:'أعمال مختارة',projectsHeading:'مشاريع حقيقية.<br><em>وتجربة حقيقية.</em>',projectsIntro:'مجموعة من المواقع التي بنيتها للتدريب والتجربة وتحويل الأفكار إلى تجارب تعمل بشكل فعلي.',projectCountLabel:'مشروع',searchPlaceholder:'ابحث في المشاريع...',noResults:'لم نجد مشاريع مطابقة.',tryAgain:'جرّب كلمة أخرى.',explore:'استكشف',
      aboutEyebrow:'عني',aboutHeading:'الشخص<br><em>خلف الكود.</em>',aboutLead:'مطور ويب شاب أتعلم من خلال بناء أشياء حقيقية.',aboutTitle:'أحب تحويل الأفكار إلى مواقع يستطيع الناس استخدامها فعلًا.',aboutBody:'أستمتع بتحويل الفكرة من صفحة فارغة إلى موقع يعمل بشكل حقيقي. أغلب خبرتي جاءت من تنفيذ مشاريع فعلية وتجربة الواجهات والتعلم من خلال النشر. أعمل حاليًا باستخدام HTML وCSS وJavaScript وFirebase، وأستخدم GitHub لنشر أعمالي وأدوات الذكاء الاصطناعي للمساعدة في بعض مراحل التطوير.',aboutBody2:'خطوتي التعليمية القادمة هي React وBootstrap. لا أريد التوقف عند معرفة الأكواد فقط، بل أريد تطوير طريقة تفكيري في بناء الواجهات والتفاعل والأداء والتجربة كاملة.',value1Title:'ابنِ أشياء حقيقية',value1Text:'المشاريع هي طريقتي في التعلم. أفضل بناء شيء يعمل ثم تحسينه بالممارسة.',value2Title:'استمر في التعلم',value2Text:'تطوير الويب يتغير باستمرار، لذلك أضيف أدوات وأفكارًا جديدة إلى طريقة عملي.',value3Title:'اهتم بالتفاصيل',value3Text:'المسافات الجيدة والتسلسل البصري والتفاعلات المفيدة تجعل الموقع البسيط أفضل بكثير.',quote:'«استمر في البناء. كل مشروع يعلمك شيئًا لم يكن المشروع السابق قادرًا على تعليمك.»',
      skillsEyebrow:'المهارات',skillsPageHeading:'الأدوات التي أستخدمها<br><em>وأتعلمها.</em>',skillsPageIntro:'نظرة واضحة على التقنيات الموجودة في طريقة عملي الحالية والتقنيات التي أتعلمها بعد ذلك.',currentSkillsTitle:'أستخدم حاليًا',currentSkillsText:'التقنيات التي أستخدمها في مشاريعي اليوم.',learningTitle:'أتعلم حاليًا',learningText:'الأدوات القادمة التي أضيفها إلى مجموعة مهاراتي.',skillNoteTitle:'بدون نسب وهمية.<br><em>تقدم حقيقي.</em>',skillNoteText:'أفضل أن أوضح ما أستخدمه فعلًا وما أتعلمه حاليًا بدل اختراع مستويات خبرة غير حقيقية.',
      contactEyebrow:'تواصل معي',contactHeading:'خلينا نبني<br><em>شيئًا حقيقيًا.</em>',contactIntro:'عندك مشروع أو تعاون أو فكرة تريد مناقشتها؟ ابعتلي رسالة.',phoneLabel:'الهاتف',callNow:'اتصل بي ↗',whatsappCta:'راسلني على واتساب ↗',youtubeCta:'زيارة القناة ↗',formHeading:'ابعتلي<br><em>رسالة.</em>',formIntro:'املأ النموذج وستُرسل رسالتك من خلال نظام الرسائل الموجود في الموقع.',formName:'الاسم',formEmail:'البريد الإلكتروني',formMessage:'الرسالة',formSend:'إرسال الرسالة',contactBottomTitle:'متاح لفرص جديدة،<br><em>وتعاونات ومشاريع ويب.</em>',seeWork:'شاهد أعمالي',backProjects:'← العودة للمشاريع',
      signedOut:'سجّل الدخول أولًا لإرسال الرسالة، حتى تظل الرسالة مرتبطة بحسابك.',sent:'تم إرسال الرسالة بنجاح.',formError:'حدث خطأ. حاول مرة أخرى.',messageRequired:'أكمل كل البيانات من فضلك.',projectNotFound:'المشروع غير موجود.'
    }
  };
  let lang = localStorage.getItem('moaaz-language') || 'en';
  let theme = localStorage.getItem('moaaz-theme') || 'dark';
  const t = k => (I18N[lang]||I18N.en)[k] || k;
  const esc = v => String(v ?? '').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const setTheme = v => {theme=v;document.documentElement.dataset.theme=v;localStorage.setItem('moaaz-theme',v)};
  function applyLang(){
    document.documentElement.lang=lang; document.documentElement.dir=lang==='ar'?'rtl':'ltr';
    document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t(el.dataset.i18n));
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));
    document.querySelectorAll('#langBtn,#mobileLangBtn').forEach(b=>b.textContent=lang==='en'?'AR':'EN');
    document.title = lang==='en' ? 'Moaaz Tamer — Full Stack Developer & Web Creator' : 'معاذ تامر — مطور Full Stack وصانع تجارب ويب';
    document.querySelectorAll('.desktop-nav a,.mobile-menu nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===document.body.dataset.page));
    renderAll();
  }
  function renderSkills(){
    const cur=document.getElementById('currentSkills'), learn=document.getElementById('learningSkills'), home=document.getElementById('homeSkills');
    const card=s=>`<article class="skill-card"><span class="skill-icon">${esc(s.icon)}</span><div><strong>${esc(s.name)}</strong><small>${lang==='en'?'Used in current projects':'مستخدم في المشاريع الحالية'}</small></div></article>`;
    const learnCard=s=>`<article class="skill-card learning"><span class="skill-icon">${esc(s.icon)}</span><div><strong>${esc(s.name)}</strong><small>${lang==='en'?'Currently learning':'أتعلمه حاليًا'}</small></div><span class="learning-dot"></span></article>`;
    if(cur)cur.innerHTML=P.currentSkills.map(card).join(''); if(learn)learn.innerHTML=P.learning.map(learnCard).join(''); if(home)home.innerHTML=[...P.currentSkills.slice(0,6),...P.learning.slice(0,2)].map(s=>`<span class="skill-pill">${esc(s.name)}</span>`).join('');
  }
  function card(p,index){
    const name=p.name?.[lang]||p.name?.en||p.slug; const desc=p.desc?.[lang]||p.desc?.en||''; const cat=p.cat?.[lang]||p.cat?.en||'';
    return `<article class="project-card reveal"><a class="project-cover" href="${encodeURI(p.path||'#')}" target="_blank" rel="noopener"><img src="${esc(p.cover)}" alt="${esc(name)}" loading="lazy"><span class="project-index">${String(index+1).padStart(2,'0')}</span><span class="project-cover-shade"></span><span class="explore-chip">${t('explore')} ↗</span></a><div class="project-body"><div class="project-meta"><span>${esc(cat)}</span><span>HTML / CSS / JS</span></div><h3>${esc(name)}</h3><p>${esc(desc)}</p><a class="text-link" href="${encodeURI(p.path||'#')}" target="_blank" rel="noopener">${t('explore')} ↗</a></div></article>`;
  }
  function renderProjects(){
    const grid=document.getElementById('projectGrid'), featured=document.getElementById('featuredGrid'); if(!grid&&!featured)return;
    const q=(document.getElementById('searchInput')?.value||'').trim().toLowerCase();
    const filtered=projects.filter(p=>!q||JSON.stringify(p).toLowerCase().includes(q));
    if(grid){grid.innerHTML=filtered.map((p,i)=>card(p,projects.indexOf(p))).join('');const empty=document.getElementById('emptyState');if(empty)empty.hidden=filtered.length>0;const c=document.getElementById('projectCount');if(c)c.textContent=projects.length;}
    if(featured)featured.innerHTML=projects.slice(0,4).map((p,i)=>card(p,i)).join('');
    observeReveal();
  }
  function renderDetail(){
    const el=document.getElementById('projectDetail'); if(!el)return;
    const id=new URLSearchParams(location.search).get('id'); const p=projects.find(x=>x.slug===id); if(!p){el.innerHTML=`<div class="empty-state"><strong>404</strong><h2>${t('projectNotFound')}</h2></div>`;return;}
    const name=p.name?.[lang]||p.name?.en||p.slug,desc=p.desc?.[lang]||p.desc?.en||'',cat=p.cat?.[lang]||p.cat?.en||'';
    el.innerHTML=`<div class="project-detail-hero"><span class="eyebrow">${esc(cat)}</span><h1>${esc(name)}</h1><p>${esc(desc)}</p><a class="btn btn-primary" href="${encodeURI(p.path||'#')}" target="_blank" rel="noopener">${t('explore')} ↗</a></div><div class="detail-cover"><img src="${esc(p.cover)}" alt="${esc(name)}"></div>`;
  }
  function bindForm(){
    const form=document.getElementById('messageForm'); if(!form||form.dataset.bound)return;form.dataset.bound='1';
    form.addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('messageStatus');const name=document.getElementById('contactName').value.trim(),email=document.getElementById('contactEmail').value.trim(),message=document.getElementById('contactMessage').value.trim();if(!name||!email||!message){status.textContent=t('messageRequired');return;}try{await window.MOAAZ_AUTH?.ready;const user=window.MOAAZ_AUTH?.auth?.currentUser;if(!user){status.innerHTML=`${t('signedOut')} <a href="login.html">${lang==='en'?'Sign in ↗':'تسجيل الدخول ↗'}</a>`;return;}await window.MOAAZ_AUTH.sendMessage(`Name: ${name}\nEmail: ${email}\n\n${message}`);form.reset();status.textContent=t('sent');}catch(err){status.textContent=window.MOAAZ_AUTH?.authErrorMessage?.(err)||t('formError');}});
  }
  function openMenu(open){const m=document.getElementById('mobileMenu'),b=document.getElementById('mobileMenuBtn');if(!m||!b)return;m.classList.toggle('open',open);m.setAttribute('aria-hidden',String(!open));b.classList.toggle('open',open);b.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)}
  function bindUI(){
    document.getElementById('themeBtn')?.addEventListener('click',()=>setTheme(theme==='dark'?'light':'dark'));document.getElementById('mobileThemeBtn')?.addEventListener('click',()=>setTheme(theme==='dark'?'light':'dark'));
    document.getElementById('langBtn')?.addEventListener('click',()=>{lang=lang==='en'?'ar':'en';localStorage.setItem('moaaz-language',lang);applyLang()});document.getElementById('mobileLangBtn')?.addEventListener('click',()=>{lang=lang==='en'?'ar':'en';localStorage.setItem('moaaz-language',lang);applyLang()});
    document.getElementById('mobileMenuBtn')?.addEventListener('click',()=>openMenu(!document.getElementById('mobileMenu')?.classList.contains('open')));document.querySelectorAll('#mobileMenu a').forEach(a=>a.addEventListener('click',()=>openMenu(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape')openMenu(false)});document.addEventListener('click',e=>{const m=document.getElementById('mobileMenu'),b=document.getElementById('mobileMenuBtn');if(m?.classList.contains('open')&&!m.contains(e.target)&&!b.contains(e.target))openMenu(false)});
    document.getElementById('searchInput')?.addEventListener('input',renderProjects);bindForm();
  }
  function observeReveal(){const els=document.querySelectorAll('.reveal:not(.is-visible)');if(!('IntersectionObserver' in window)){els.forEach(e=>e.classList.add('is-visible'));return;}const io=new IntersectionObserver(entries=>entries.forEach(en=>{if(en.isIntersecting){en.target.classList.add('is-visible');io.unobserve(en.target)}}),{threshold:.12});els.forEach(e=>io.observe(e));}
  function renderAll(){renderSkills();renderProjects();renderDetail();observeReveal();}
  setTheme(theme);bindUI();document.getElementById('year').textContent=new Date().getFullYear();applyLang();
})();
